[package]
name = "pmtconcon-studio"
version = "0.2.0"
description = "PMTCONCON Studio desktop app"
authors = ["PMTCONCON Studio"]
edition = "2021"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "pmtconcon_studio_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["protocol-asset"] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rusqlite = { version = "0.39.0", features = ["bundled"] }
image = "0.25.10"
gif = "0.14.2"
fast_image_resize = "6.0.0"
sha2 = "0.10.9"
rfd = "0.15.4"
fontdue = { version = "0.9.3", default-features = false }
